apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-app-config
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}