apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.vote.service.type }}
  selector:
    app: vote
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.containerPort }}
